// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolyDatabase;

#nullable disable

namespace PolyDatabase.Migrations
{
    [DbContext(typeof(PolyContext))]
    [Migration("20230129163255_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PolyDatabase.Grade", b =>
                {
                    b.Property<string>("Subject_id")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Appr")
                        .HasColumnType("longtext");

                    b.Property<float?>("Class_avg")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Date_str")
                        .HasColumnType("longtext");

                    b.Property<string>("Rank")
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext");

                    b.Property<float?>("grade")
                        .HasColumnType("float");

                    b.HasKey("Subject_id", "Name");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("PolyDatabase.Newsletter", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Calendar")
                        .HasColumnType("longtext");

                    b.Property<ulong>("Id")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("UserId");

                    b.ToTable("Newsletters");
                });

            modelBuilder.Entity("PolyDatabase.Server", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("NewsChannel")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });
#pragma warning restore 612, 618
        }
    }
}
